{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-secrets" .Release.Name)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  postgres-password: {{ if and (not $existingSecret) (not .Values.postgres.password) }}{{ include "rybbit.randomPassword" . | b64enc | quote }}{{ else }}{{ .Values.postgres.password | default (index $existingSecret.data "postgres-password") | b64enc | quote }}{{ end }}
  postgres-user: {{ .Values.postgres.user | default "frog" | b64enc | quote }}
  clickhouse-password: {{ if and (not $existingSecret) (not .Values.clickhouse.password) }}{{ include "rybbit.randomPassword" . | b64enc | quote }}{{ else }}{{ .Values.clickhouse.password | default (index $existingSecret.data "clickhouse-password") | b64enc | quote }}{{ end }}
  clickhouse-user: {{ .Values.clickhouse.user | default "default" | b64enc | quote }}
  better-auth-secret: {{ if and (not $existingSecret) (not .Values.backend.env.BETTER_AUTH_SECRET) }}{{ include "rybbit.randomString" . | b64enc | quote }}{{ else }}{{ .Values.backend.env.BETTER_AUTH_SECRET | default (index $existingSecret.data "better-auth-secret") | b64enc | quote }}{{ end }} 